name: Trigger API on Push

on:
  push:
    branches:
      - dev  # ou la branche que vous souhaitez surveiller

jobs:
  trigger_api:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}  # Adresse IP de votre Raspberry Pi
          username: ${{ secrets.RASPBERRY_PI_USER }}  # Utilisateur SSH
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Clé privée SSH
          script: |
            python3 /var/www/html/PoleInfo/poleinfo_api/main.py
